# Generated by Django 4.2.6 on 2023-11-16 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='광고제목')),
                ('host', models.CharField(max_length=20, verbose_name='광고협찬사')),
                ('host_email', models.EmailField(max_length=50, verbose_name='광고협찬사 이메일')),
                ('content', models.TextField(verbose_name='상세내용')),
                ('ad_image', models.ImageField(blank=True, null=True, upload_to='ad', verbose_name='광고 이미지')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='행사명')),
                ('host', models.CharField(max_length=20, verbose_name='주최사명')),
                ('host_email', models.EmailField(max_length=50, verbose_name='주최사 이메일')),
                ('field', models.CharField(max_length=10, verbose_name='행사분야')),
                ('category', models.CharField(max_length=10, verbose_name='행사유형')),
                ('size', models.CharField(max_length=10, verbose_name='행사규모')),
                ('introduce', models.TextField(verbose_name='행사소개')),
                ('date', models.DateTimeField(verbose_name='행사날짜')),
                ('on_off', models.CharField(max_length=10, verbose_name='온오프라인')),
                ('deadline', models.DateTimeField(verbose_name='협찬마감일')),
                ('detail_location', models.CharField(max_length=30, verbose_name='상세주소')),
                ('sponsor_category', models.CharField(max_length=20, verbose_name='협찬 종류')),
                ('sponsor_advantage', models.TextField(verbose_name='협찬 혜택')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event', verbose_name='행사 대표 이미지')),
                ('participant', models.TextField(blank=True, verbose_name='참가자 기술')),
                ('participant_recruit', models.TextField(blank=True, verbose_name='참가자 모집 방법')),
                ('last_event', models.TextField(blank=True, verbose_name='행사 기록')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='events',
        ),
    ]
