# Generated by Django 4.2.6 on 2023-11-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_advertise_event_delete_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recommends',
            field=models.IntegerField(default=0, verbose_name='추천정도'),
        ),
    ]
