# Generated by Django 4.2.6 on 2023-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_advertise_event_delete_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recommends',
            field=models.IntegerField(default=0, verbose_name='추천정도'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='ad_image',
            field=models.ImageField(blank=True, null=True, upload_to='ad/', verbose_name='광고 이미지'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event/', verbose_name='행사 대표 이미지'),
        ),
    ]
