# Generated by Django 4.2.6 on 2023-11-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_recommends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='ad_image',
            field=models.ImageField(blank=True, null=True, upload_to='ad/', verbose_name='광고 이미지'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event/', verbose_name='행사 대표 이미지'),
        ),
    ]
